import path from 'node:path';
import { createSnapshot } from './snapshot.js';
import type { DependencySpec, Finding, ScanResult, Severity } from './types.js';

const riskySpecPatterns: Array<{
  id: string;
  title: string;
  severity: Severity;
  test: (spec: string) => boolean;
  detail: (dependency: DependencySpec) => string;
  recommendation: string;
}> = [
  {
    id: 'unpinned-latest',
    title: 'Dependency uses latest tag',
    severity: 'high',
    test: (spec) => spec.trim() === 'latest',
    detail: (dependency) => `${dependency.name} in ${dependency.section} uses the moving latest tag.`,
    recommendation: 'Pin the dependency to a reviewed semver range or exact version.'
  },
  {
    id: 'wildcard-range',
    title: 'Dependency uses wildcard range',
    severity: 'medium',
    test: (spec) => ['*', 'x', 'X'].includes(spec.trim()) || /(^|[.~^>=< -])x(\.|$)/i.test(spec),
    detail: (dependency) => `${dependency.name} in ${dependency.section} uses a wildcard version range (${dependency.spec}).`,
    recommendation: 'Use a narrower semver range that matches versions reviewed in the lockfile.'
  },
  {
    id: 'remote-source',
    title: 'Dependency installs from a remote source',
    severity: 'high',
    test: (spec) => /^(git\+|github:|gitlab:|bitbucket:|https?:)/i.test(spec),
    detail: (dependency) => `${dependency.name} in ${dependency.section} installs from ${dependency.spec}.`,
    recommendation: 'Prefer registry packages with immutable lockfile integrity when possible.'
  },
  {
    id: 'local-path',
    title: 'Dependency installs from a local path',
    severity: 'medium',
    test: (spec) => /^(file:|link:|workspace:)/i.test(spec),
    detail: (dependency) => `${dependency.name} in ${dependency.section} resolves from a local workspace or path (${dependency.spec}).`,
    recommendation: 'Verify the local package is expected and included in release review.'
  }
];

export async function scanProject(root: string): Promise<ScanResult> {
  const absoluteRoot = path.resolve(root);
  const snapshot = await createSnapshot(absoluteRoot);
  const findings = collectFindings(snapshot.dependencies, snapshot.lockfile);
  const summary = findings.reduce(
    (counts, finding) => {
      counts[finding.severity] += 1;
      return counts;
    },
    { dependencyCount: snapshot.dependencies.length, lockedPackageCount: snapshot.lockfile.packageCount, high: 0, medium: 0, low: 0 }
  );

  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    root: absoluteRoot,
    summary,
    snapshot,
    findings
  };
}

function collectFindings(
  dependencies: DependencySpec[],
  lockfile: ScanResult['snapshot']['lockfile']
): Finding[] {
  const findings: Finding[] = [];

  if (dependencies.length > 0 && lockfile.kind === 'none') {
    findings.push({
      id: 'missing-lockfile',
      title: 'Project has dependencies without a lockfile',
      severity: 'high',
      detail: 'package.json declares dependencies, but no npm or pnpm lockfile was found.',
      recommendation: 'Commit a package-lock.json or pnpm-lock.yaml generated by the intended package manager.'
    });
  }

  for (const dependency of dependencies) {
    for (const rule of riskySpecPatterns) {
      if (rule.test(dependency.spec)) {
        findings.push({
          id: rule.id,
          title: rule.title,
          severity: rule.severity,
          packageName: dependency.name,
          section: dependency.section,
          detail: rule.detail(dependency),
          recommendation: rule.recommendation
        });
      }
    }
  }

  const declared = new Set(dependencies.map((dependency) => dependency.name));
  const locked = new Set(lockfile.packages.map((pkg) => pkg.name));

  for (const dependency of dependencies) {
    if (lockfile.kind !== 'none' && !locked.has(dependency.name)) {
      findings.push({
        id: 'dependency-not-locked',
        title: 'Declared dependency is missing from lockfile',
        severity: 'medium',
        packageName: dependency.name,
        section: dependency.section,
        detail: `${dependency.name} is declared in ${dependency.section}, but it was not found in the ${lockfile.kind} lockfile.`,
        recommendation: 'Regenerate the lockfile with the intended package manager and review the resulting package churn.'
      });
    }
  }

  for (const pkg of lockfile.packages) {
    if (pkg.hasInstallScript) {
      findings.push({
        id: 'install-script',
        title: 'Locked package has an install/build script',
        severity: 'medium',
        packageName: pkg.name,
        detail: `${pkg.name}${pkg.version ? `@${pkg.version}` : ''} is marked as requiring an install or build script.`,
        recommendation: 'Review the package before install and confirm the script is expected.'
      });
    }
  }

  if (lockfile.kind !== 'none' && dependencies.length > 0) {
    const missingFromManifest = lockfile.packages
      .filter((pkg) => declared.has(pkg.name) === false)
      .slice(0, 5);

    for (const pkg of missingFromManifest) {
      findings.push({
        id: 'transitive-package',
        title: 'Transitive package present in lockfile',
        severity: 'low',
        packageName: pkg.name,
        detail: `${pkg.name}${pkg.version ? `@${pkg.version}` : ''} is present in the lockfile as a transitive dependency.`,
        recommendation: 'Include this package in dependency review when lockfile churn changes.'
      });
    }
  }

  return findings.sort((left, right) => severityWeight(right.severity) - severityWeight(left.severity) || left.id.localeCompare(right.id));
}

function severityWeight(severity: Severity): number {
  switch (severity) {
    case 'high':
      return 3;
    case 'medium':
      return 2;
    case 'low':
      return 1;
  }
}
